# Generated by Django 5.2.18 on 2026-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvo_data', models.TextField(blank=True, verbose_name='94 Данные для Солво')),
                ('uip', models.CharField(blank=True, max_length=64, verbose_name='95 УИП')),
                ('cargo', models.CharField(blank=True, max_length=64, verbose_name='96 Номер груза')),
                ('pallet', models.CharField(blank=True, max_length=64, verbose_name='97 Номер паллеты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Скан паллеты',
                'verbose_name_plural': 'Сканы паллет',
                'ordering': ['-created_at'],
            },
        ),
    ]
